# Generated by Django 5.2.10 on 2026-01-20 02:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('sigla', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('PROFISSIONAL', 'Profissional'), ('ESCALANTE', 'Escalante'), ('CHEFE', 'Chefe de Setor'), ('ADMIN', 'Administrador')], default='PROFISSIONAL', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setores', to='cal.hospital')),
            ],
            options={
                'verbose_name_plural': 'Setores',
                'unique_together': {('nome', 'hospital')},
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('nome_exibicao', models.CharField(help_text='Nome para o calendário', max_length=50)),
                ('carga_horaria_semanal', models.PositiveIntegerField(default=40)),
                ('hospitais', models.ManyToManyField(related_name='profissionais', to='cal.hospital')),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matricula', to='cal.perfilusuario')),
                ('setores', models.ManyToManyField(related_name='profissionais', to='cal.setor')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(max_length=200)),
                ('horas', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(24)])),
                ('cor_hex', models.CharField(default='#3498db', max_length=7)),
                ('contabiliza_carga_horaria', models.BooleanField(default=True, help_text='Se desmarcado (ex: TPD), não soma na carga horária semanal.')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cal.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='EventoEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.hospital')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='cal.matricula')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.setor')),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cal.tipoevento')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos (Escala)',
            },
        ),
    ]
