# Generated by Django 5.2.10 on 2026-01-20 03:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Especialidade')),
            ],
            options={
                'verbose_name': 'Especialidade',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Hospital')),
                ('sigla', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitais',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do Período')),
                ('sigla', models.CharField(max_length=10, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('PROFISSIONAL', 'Profissional'), ('ESCALANTE', 'Escalante'), ('CHEFE', 'Chefe de Setor'), ('ADMIN', 'Administrador')], default='PROFISSIONAL', max_length=20, verbose_name='Nível de Acesso')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do Setor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setores', to='cal.hospital', verbose_name='Hospital')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'unique_together': {('nome', 'hospital')},
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número da Matrícula')),
                ('nome_exibicao', models.CharField(help_text='Nome como aparecerá no calendário', max_length=50, verbose_name='Nome de Exibição')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('carga_horaria_semanal', models.PositiveIntegerField(default=40, help_text='Limite de horas por semana', verbose_name='Carga Horária Semanal')),
                ('especialidades', models.ManyToManyField(blank=True, related_name='matriculas', to='cal.especialidade', verbose_name='Especialidades')),
                ('hospitais', models.ManyToManyField(related_name='matriculas', to='cal.hospital', verbose_name='Hospitais Vinculados')),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matricula', to='cal.perfilusuario', verbose_name='Perfil')),
                ('setores', models.ManyToManyField(related_name='matriculas', to='cal.setor', verbose_name='Setores Alocados')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do Tipo de Evento')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código/Sigla')),
                ('horas', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='Carga Horária')),
                ('cor', models.CharField(default='#3498db', max_length=7, verbose_name='Cor no Calendário')),
                ('contabiliza_carga_horaria', models.BooleanField(default=True, verbose_name='Contabiliza Carga Horária?')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_evento', to='cal.periodo', verbose_name='Período')),
            ],
            options={
                'verbose_name': 'Tipo de Evento',
                'verbose_name_plural': 'Tipos de Eventos',
            },
        ),
        migrations.CreateModel(
            name='EventoEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='cal.hospital', verbose_name='Hospital')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='cal.matricula', verbose_name='Profissional')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='cal.setor', verbose_name='Setor')),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='cal.tipoevento', verbose_name='Tipo de Evento')),
            ],
            options={
                'verbose_name': 'Evento de Escala',
                'verbose_name_plural': 'Eventos de Escala',
            },
        ),
    ]
