# Generated by Django 5.2.1 on 2025-05-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "start_time",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de início"
                    ),
                ),
            ],
        ),
    ]
