# Generated by Django 5.2.10 on 2026-01-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfermeiro',
            name='nome',
            field=models.CharField(default='', max_length=255),
        ),
    ]
