# Generated by Django 5.2.1 on 2025-05-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="end_time",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de início"
            ),
        ),
    ]
