# Generated by Django 5.2.10 on 2026-01-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='numero',
            field=models.CharField(max_length=50, unique=True, verbose_name='Matrícula'),
        ),
    ]
