# Generated by Django 6.0.1 on 2026-01-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Especialidade')),
            ],
            options={
                'verbose_name': 'Especialidade',
                'verbose_name_plural': 'Especialidades',
            },
        ),
    ]
