# Generated by Django 5.2.10 on 2026-01-16 06:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_enfermeiro_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='pode_aprovar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='data_solicitacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20),
        ),
    ]
