# Generated by Django 5.2.10 on 2026-01-20 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_alter_matricula_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas', to='cal.perfilusuario', verbose_name='Perfil'),
        ),
    ]
