# Generated by Django 5.2.10 on 2026-01-15 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_remove_event_end_time_alter_event_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_hospital', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPlantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Normal', 'Normal'), ('TPD', 'TPD')], max_length=10)),
                ('periodo', models.CharField(choices=[('SM', 'Manhã'), ('ST', 'Tarde'), ('SN', 'Noite')], max_length=2)),
                ('qtd_horas', models.IntegerField(choices=[(6, '6h'), (12, '12h')])),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título do Evento'),
        ),
        migrations.CreateModel(
            name='Enfermeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=50)),
                ('carga_horaria', models.IntegerField(help_text='Carga horária mensal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
                ('hospitais', models.ManyToManyField(to='cal.hospital')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='enfermeiro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='cal.enfermeiro'),
        ),
        migrations.AddField(
            model_name='event',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cal.hospital'),
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_setor', models.CharField(max_length=200)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setores', to='cal.hospital')),
            ],
        ),
        migrations.AddField(
            model_name='enfermeiro',
            name='setores',
            field=models.ManyToManyField(to='cal.setor'),
        ),
        migrations.AddField(
            model_name='event',
            name='setor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cal.setor'),
        ),
        migrations.AddField(
            model_name='event',
            name='tipo_plantao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cal.tipoplantao'),
        ),
    ]
