# Generated by Django 5.2.10 on 2026-01-20 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_alter_matricula_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='especialidades',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='hospitais',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='setores',
        ),
        migrations.AddField(
            model_name='matricula',
            name='especialidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas', to='cal.especialidade', verbose_name='Especialidade'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='cal.hospital', verbose_name='Hospital Vinculado'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='cal.setor', verbose_name='Setor Alocado'),
        ),
    ]
