# Generated by Django 5.2.10 on 2026-01-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_perfilusuario_pode_aprovar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantao',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantao',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
