# Generated by Django 5.2.10 on 2026-01-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_hospital_tipoplantao_alter_event_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoplantao',
            name='periodo',
            field=models.CharField(choices=[('SM', 'Manhã'), ('ST', 'Tarde'), ('SN', 'Noite'), ('SD', 'Dia')], max_length=2),
        ),
    ]
