# Generated by Django 6.0.1 on 2026-01-20 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_remove_matricula_especialidades_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoescala',
            name='cor',
            field=models.CharField(default='#3498db', help_text='Cor específica para este evento', max_length=7, verbose_name='Cor Personalizada'),
        ),
        migrations.AlterField(
            model_name='eventoescala',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meus_eventos', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
    ]
