# Generated by Django 6.0.1 on 2026-01-22 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_perfilusuario_matricula_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='especialidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profissionais', to='cal.especialidade'),
        ),
    ]
