# Generated by Django 6.0.1 on 2026-01-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0005_matricula_especialidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matricula',
            options={'ordering': ['nome_exibicao']},
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='nome_guerra',
        ),
        migrations.AddField(
            model_name='matricula',
            name='nome_exibicao',
            field=models.CharField(default='', max_length=50, verbose_name='Nome de Exibição'),
        ),
    ]
