# Generated by Django 5.2.10 on 2026-01-19 19:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0005_especialidade_enfermeiro_especialidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_evento', models.CharField(max_length=50)),
                ('periodo_evento_sigla', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='plantao',
            name='tipo_plantao',
        ),
        migrations.RemoveField(
            model_name='enfermeiro',
            name='especialidade',
        ),
        migrations.RemoveField(
            model_name='enfermeiro',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='sigla',
        ),
        migrations.RemoveField(
            model_name='plantao',
            name='hora_fim',
        ),
        migrations.RemoveField(
            model_name='plantao',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='enfermeiro',
            name='especialidades',
            field=models.ManyToManyField(blank=True, related_name='enfermeiros_especialidades', to='cal.especialidade'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='nome_hospital_sigla',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enfermeiro',
            name='hospitais',
            field=models.ManyToManyField(related_name='hospital_enfermeiros', to='cal.hospital'),
        ),
        migrations.AlterField(
            model_name='enfermeiro',
            name='nome',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='enfermeiro',
            name='perfil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enfermeiro_perfil', to='cal.perfilusuario'),
        ),
        migrations.AlterField(
            model_name='enfermeiro',
            name='setores',
            field=models.ManyToManyField(related_name='setor_enfermeiros', to='cal.setor'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='nome_hospital',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='setor',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setores_hospital', to='cal.hospital'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='nome_setor',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='enfermeiro',
            name='matriculas',
            field=models.ManyToManyField(related_name='enfermeiro_matriculas', to='cal.matricula'),
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(max_length=50)),
                ('tipo_evento_sigla', models.CharField(max_length=20)),
                ('codigo', models.CharField(default='', max_length=20)),
                ('descricao', models.CharField(default='', max_length=200)),
                ('horas', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('cor', models.CharField(default='#3498db', max_length=7)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodo_evento_rel', to='cal.periodo')),
            ],
        ),
        migrations.AddField(
            model_name='plantao',
            name='tipo_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cal.tipoevento'),
        ),
        migrations.DeleteModel(
            name='Solicitacao',
        ),
        migrations.DeleteModel(
            name='TipoPlantao',
        ),
    ]
