# Generated by Django 6.0.1 on 2026-01-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0006_alter_eventoescala_criado_por_alter_matricula_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('PROFISSIONAL', 'Enfermeiro'), ('ESCALANTE', 'Escalante'), ('CHEFE', 'Chefe de Setor'), ('ADMIN', 'Administrador')], default='PROFISSIONAL', max_length=20, verbose_name='Nível de Acesso'),
        ),
    ]
