# Generated by Django 6.0.1 on 2026-01-22 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0006_alter_matricula_options_remove_matricula_nome_guerra_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoevento',
            options={'verbose_name': 'Tipo de Evento', 'verbose_name_plural': 'Tipos de Evento'},
        ),
        migrations.RemoveField(
            model_name='tipoevento',
            name='contabiliza',
        ),
        migrations.AlterField(
            model_name='tipoevento',
            name='codigo',
            field=models.CharField(max_length=10, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='tipoevento',
            name='cor',
            field=models.CharField(default='primary', max_length=20, verbose_name='Cor (Bootstrap)'),
        ),
        migrations.AlterField(
            model_name='tipoevento',
            name='descricao',
            field=models.CharField(max_length=50, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tipoevento',
            name='horas',
            field=models.PositiveIntegerField(verbose_name='Carga Horária (Horas)'),
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10, verbose_name='Sigla do Tipo')),
                ('tipo_descricao', models.CharField(max_length=50, verbose_name='Descrição do Tipo')),
                ('contabiliza', models.BooleanField(default=True, verbose_name='Contabiliza Carga Horária?')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'unique_together': {('tipo', 'tipo_descricao')},
            },
        ),
        migrations.AddField(
            model_name='tipoevento',
            name='tipo_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='cal.tipo', verbose_name='Tipo Base'),
        ),
    ]
