# Generated by Django 6.0.1 on 2026-01-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0007_alter_perfilusuario_tipo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='user',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nome',
            field=models.CharField(default='Sem Nome', max_length=255, verbose_name='Nome'),
        ),
    ]
