# Generated by Django 5.2.10 on 2026-01-28 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0007_alter_tipoevento_options_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegislacaoTPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='tipoevento',
            name='cor',
            field=models.CharField(choices=[('#007bff', 'Azul'), ('#6610f2', 'Roxo'), ('#6f42c1', 'Lilás'), ('#e83e8c', 'Rosa'), ('#dc3545', 'Vermelho'), ('#fd7e14', 'Laranja'), ('#ffc107', 'Amarelo'), ('#28a745', 'Verde'), ('#20c997', 'Turquesa'), ('#17a2b8', 'Ciano'), ('#6c757d', 'Cinza'), ('#343a40', 'Preto')], default='#007bff', max_length=20, verbose_name='Cor'),
        ),
        migrations.CreateModel(
            name='TPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('horas_trabalhadas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('horas_noturnas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valor_hora', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('adicional_tpd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adicional_noturno', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('violacao_regra', models.BooleanField(default=False)),
                ('mensagem_erro', models.TextField(blank=True, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.hospital')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpds', to='cal.matricula')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.setor')),
            ],
        ),
    ]
