# Generated by Django 5.2.10 on 2026-01-29 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0008_legislacaotpd_alter_tipoevento_cor_tpd'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')])),
                ('ano', models.IntegerField()),
                ('arquivo_excel', models.FileField(blank=True, null=True, upload_to='escalas/%Y/%m/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospital')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.setor')),
            ],
            options={
                'verbose_name': 'Escala Mensal',
                'verbose_name_plural': 'Escalas Mensais',
                'unique_together': {('mes', 'ano', 'hospital', 'setor')},
            },
        ),
        migrations.CreateModel(
            name='DiaEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('turnos', models.CharField(blank=True, max_length=50)),
                ('horas_dia', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('e_tpd', models.BooleanField(default=False)),
                ('e_folga', models.BooleanField(default=False)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.matricula')),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='cal.escalamensal')),
            ],
        ),
        migrations.CreateModel(
            name='ControleSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_numero', models.IntegerField()),
                ('carga_semanal', models.IntegerField(default=40)),
                ('carga_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('horas_realizadas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('horas_tpd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('horas_tpd_noturno', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.matricula')),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='cal.escalamensal')),
            ],
        ),
        migrations.CreateModel(
            name='MapeamentoTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla_excel', models.CharField(max_length=20, unique=True)),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.tipoevento')),
            ],
        ),
    ]
