# Generated by Django 6.0.1 on 2026-01-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0008_remove_perfilusuario_user_perfilusuario_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome do Perfil'),
        ),
    ]
