# Generated by Django 6.0.1 on 2026-02-01 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0009_escalamensal_diaescala_controlesemanal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoescala',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.tipoevento'),
        ),
    ]
