# Generated by Django 5.2.10 on 2026-03-24 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0010_alter_eventoescala_tipo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="LegislacaoTPD",
        ),
        migrations.AlterModelOptions(
            name="tpd",
            options={
                "ordering": ["-data"],
                "verbose_name": "TPD",
                "verbose_name_plural": "TPDs",
            },
        ),
        migrations.RemoveField(
            model_name="tpd",
            name="adicional_noturno",
        ),
        migrations.RemoveField(
            model_name="tpd",
            name="horas_noturnas",
        ),
        migrations.RemoveField(
            model_name="tpd",
            name="mensagem_erro",
        ),
        migrations.RemoveField(
            model_name="tpd",
            name="violacao_regra",
        ),
        migrations.AddField(
            model_name="tpd",
            name="criado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tpds_criados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
