# Generated by Django 5.2.10 on 2026-04-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0011_tpd_remove_regras_add_criado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoevento',
            name='horas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Carga Horária (Horas)'),
        ),
    ]
